#!/usr/bin/env node
/**
 * generated by the opake compiler
 */

"use strict";

var Machine = require('./Machine');
var System = require('./System');

var system = new System();

// create machines to model the OS environment

var stdout = system.createMachine(function (body) {
    process.stdout.write("" + body);
});

var stderr = system.createMachine(function (body) {
    process.stderr.write("" + body);
});

var exitCode = 0;

// this machine just stores the exit code
var out = system.createMachine(function (body) {
});

var err = system.createMachine(function (body) {
    exitCode = 1;
});

var io = {
    _out: stdout,
    _err: stderr
};

var main = function () {console.log("I think you ought to know I'm feeling very depressed.")};

// BEGIN GENERATED CODE

//<<CODE>>

// END GENERATED CODE

// create a machine for the compiled source
var root = system.createMachine(main);

// send the launch message to the machine
// todo make this a real message
system.sendMessage(root, [process.argv, io, process.env], out, err);

// run the machine
system.run();

process.exit(exitCode);